[project]
name = "cafeteria"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi[standard]>=0.133.1",
    "psycopg-pool>=3.3.0",
    "psycopg[binary,pool]>=3.3.3",
    "uvicorn>=0.41.0",
]
